package rpc.iface;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-08-12")
public class FilteredResult implements org.apache.thrift.TBase<FilteredResult, FilteredResult._Fields>, java.io.Serializable, Cloneable, Comparable<FilteredResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FilteredResult");

  private static final org.apache.thrift.protocol.TField FILTERED_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("filteredNum", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField UPDATED_SWF_FIELD_DESC = new org.apache.thrift.protocol.TField("updatedSWF", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FilteredResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FilteredResultTupleSchemeFactory();

  public int filteredNum; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer updatedSWF; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILTERED_NUM((short)1, "filteredNum"),
    UPDATED_SWF((short)2, "updatedSWF");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILTERED_NUM
          return FILTERED_NUM;
        case 2: // UPDATED_SWF
          return UPDATED_SWF;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FILTEREDNUM_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILTERED_NUM, new org.apache.thrift.meta_data.FieldMetaData("filteredNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.UPDATED_SWF, new org.apache.thrift.meta_data.FieldMetaData("updatedSWF", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FilteredResult.class, metaDataMap);
  }

  public FilteredResult() {
  }

  public FilteredResult(
    int filteredNum,
    java.nio.ByteBuffer updatedSWF)
  {
    this();
    this.filteredNum = filteredNum;
    setFilteredNumIsSet(true);
    this.updatedSWF = org.apache.thrift.TBaseHelper.copyBinary(updatedSWF);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FilteredResult(FilteredResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.filteredNum = other.filteredNum;
    if (other.isSetUpdatedSWF()) {
      this.updatedSWF = org.apache.thrift.TBaseHelper.copyBinary(other.updatedSWF);
    }
  }

  @Override
  public FilteredResult deepCopy() {
    return new FilteredResult(this);
  }

  @Override
  public void clear() {
    setFilteredNumIsSet(false);
    this.filteredNum = 0;
    this.updatedSWF = null;
  }

  public int getFilteredNum() {
    return this.filteredNum;
  }

  public FilteredResult setFilteredNum(int filteredNum) {
    this.filteredNum = filteredNum;
    setFilteredNumIsSet(true);
    return this;
  }

  public void unsetFilteredNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FILTEREDNUM_ISSET_ID);
  }

  /** Returns true if field filteredNum is set (has been assigned a value) and false otherwise */
  public boolean isSetFilteredNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FILTEREDNUM_ISSET_ID);
  }

  public void setFilteredNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FILTEREDNUM_ISSET_ID, value);
  }

  public byte[] getUpdatedSWF() {
    setUpdatedSWF(org.apache.thrift.TBaseHelper.rightSize(updatedSWF));
    return updatedSWF == null ? null : updatedSWF.array();
  }

  public java.nio.ByteBuffer bufferForUpdatedSWF() {
    return org.apache.thrift.TBaseHelper.copyBinary(updatedSWF);
  }

  public FilteredResult setUpdatedSWF(byte[] updatedSWF) {
    this.updatedSWF = updatedSWF == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(updatedSWF.clone());
    return this;
  }

  public FilteredResult setUpdatedSWF(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer updatedSWF) {
    this.updatedSWF = org.apache.thrift.TBaseHelper.copyBinary(updatedSWF);
    return this;
  }

  public void unsetUpdatedSWF() {
    this.updatedSWF = null;
  }

  /** Returns true if field updatedSWF is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdatedSWF() {
    return this.updatedSWF != null;
  }

  public void setUpdatedSWFIsSet(boolean value) {
    if (!value) {
      this.updatedSWF = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case FILTERED_NUM:
      if (value == null) {
        unsetFilteredNum();
      } else {
        setFilteredNum((java.lang.Integer)value);
      }
      break;

    case UPDATED_SWF:
      if (value == null) {
        unsetUpdatedSWF();
      } else {
        if (value instanceof byte[]) {
          setUpdatedSWF((byte[])value);
        } else {
          setUpdatedSWF((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case FILTERED_NUM:
      return getFilteredNum();

    case UPDATED_SWF:
      return getUpdatedSWF();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case FILTERED_NUM:
      return isSetFilteredNum();
    case UPDATED_SWF:
      return isSetUpdatedSWF();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof FilteredResult)
      return this.equals((FilteredResult)that);
    return false;
  }

  public boolean equals(FilteredResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_filteredNum = true;
    boolean that_present_filteredNum = true;
    if (this_present_filteredNum || that_present_filteredNum) {
      if (!(this_present_filteredNum && that_present_filteredNum))
        return false;
      if (this.filteredNum != that.filteredNum)
        return false;
    }

    boolean this_present_updatedSWF = true && this.isSetUpdatedSWF();
    boolean that_present_updatedSWF = true && that.isSetUpdatedSWF();
    if (this_present_updatedSWF || that_present_updatedSWF) {
      if (!(this_present_updatedSWF && that_present_updatedSWF))
        return false;
      if (!this.updatedSWF.equals(that.updatedSWF))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + filteredNum;

    hashCode = hashCode * 8191 + ((isSetUpdatedSWF()) ? 131071 : 524287);
    if (isSetUpdatedSWF())
      hashCode = hashCode * 8191 + updatedSWF.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(FilteredResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetFilteredNum(), other.isSetFilteredNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFilteredNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.filteredNum, other.filteredNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUpdatedSWF(), other.isSetUpdatedSWF());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdatedSWF()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updatedSWF, other.updatedSWF);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("FilteredResult(");
    boolean first = true;

    sb.append("filteredNum:");
    sb.append(this.filteredNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("updatedSWF:");
    if (this.updatedSWF == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.updatedSWF, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FilteredResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FilteredResultStandardScheme getScheme() {
      return new FilteredResultStandardScheme();
    }
  }

  private static class FilteredResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<FilteredResult> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, FilteredResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILTERED_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.filteredNum = iprot.readI32();
              struct.setFilteredNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UPDATED_SWF
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.updatedSWF = iprot.readBinary();
              struct.setUpdatedSWFIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, FilteredResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(FILTERED_NUM_FIELD_DESC);
      oprot.writeI32(struct.filteredNum);
      oprot.writeFieldEnd();
      if (struct.updatedSWF != null) {
        oprot.writeFieldBegin(UPDATED_SWF_FIELD_DESC);
        oprot.writeBinary(struct.updatedSWF);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FilteredResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FilteredResultTupleScheme getScheme() {
      return new FilteredResultTupleScheme();
    }
  }

  private static class FilteredResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<FilteredResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FilteredResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFilteredNum()) {
        optionals.set(0);
      }
      if (struct.isSetUpdatedSWF()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetFilteredNum()) {
        oprot.writeI32(struct.filteredNum);
      }
      if (struct.isSetUpdatedSWF()) {
        oprot.writeBinary(struct.updatedSWF);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FilteredResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.filteredNum = iprot.readI32();
        struct.setFilteredNumIsSet(true);
      }
      if (incoming.get(1)) {
        struct.updatedSWF = iprot.readBinary();
        struct.setUpdatedSWFIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

