package rpc.iface;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-08-04")
public class PushPullDataChunk implements org.apache.thrift.TBase<PushPullDataChunk, PushPullDataChunk._Fields>, java.io.Serializable, Cloneable, Comparable<PushPullDataChunk> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PushPullDataChunk");

  private static final org.apache.thrift.protocol.TField CHUNK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("chunkId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField VAR_EVENT_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("varEventMap", org.apache.thrift.protocol.TType.MAP, (short)2);
  private static final org.apache.thrift.protocol.TField IS_LAST_CHUNK_FIELD_DESC = new org.apache.thrift.protocol.TField("isLastChunk", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PushPullDataChunkStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PushPullDataChunkTupleSchemeFactory();

  public int chunkId; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.nio.ByteBuffer> varEventMap; // required
  public boolean isLastChunk; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CHUNK_ID((short)1, "chunkId"),
    VAR_EVENT_MAP((short)2, "varEventMap"),
    IS_LAST_CHUNK((short)3, "isLastChunk");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CHUNK_ID
          return CHUNK_ID;
        case 2: // VAR_EVENT_MAP
          return VAR_EVENT_MAP;
        case 3: // IS_LAST_CHUNK
          return IS_LAST_CHUNK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CHUNKID_ISSET_ID = 0;
  private static final int __ISLASTCHUNK_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CHUNK_ID, new org.apache.thrift.meta_data.FieldMetaData("chunkId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.VAR_EVENT_MAP, new org.apache.thrift.meta_data.FieldMetaData("varEventMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true))));
    tmpMap.put(_Fields.IS_LAST_CHUNK, new org.apache.thrift.meta_data.FieldMetaData("isLastChunk", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PushPullDataChunk.class, metaDataMap);
  }

  public PushPullDataChunk() {
  }

  public PushPullDataChunk(
    int chunkId,
    java.util.Map<java.lang.String,java.nio.ByteBuffer> varEventMap,
    boolean isLastChunk)
  {
    this();
    this.chunkId = chunkId;
    setChunkIdIsSet(true);
    this.varEventMap = varEventMap;
    this.isLastChunk = isLastChunk;
    setIsLastChunkIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PushPullDataChunk(PushPullDataChunk other) {
    __isset_bitfield = other.__isset_bitfield;
    this.chunkId = other.chunkId;
    if (other.isSetVarEventMap()) {
      java.util.Map<java.lang.String,java.nio.ByteBuffer> __this__varEventMap = new java.util.HashMap<java.lang.String,java.nio.ByteBuffer>(other.varEventMap);
      this.varEventMap = __this__varEventMap;
    }
    this.isLastChunk = other.isLastChunk;
  }

  @Override
  public PushPullDataChunk deepCopy() {
    return new PushPullDataChunk(this);
  }

  @Override
  public void clear() {
    setChunkIdIsSet(false);
    this.chunkId = 0;
    this.varEventMap = null;
    setIsLastChunkIsSet(false);
    this.isLastChunk = false;
  }

  public int getChunkId() {
    return this.chunkId;
  }

  public PushPullDataChunk setChunkId(int chunkId) {
    this.chunkId = chunkId;
    setChunkIdIsSet(true);
    return this;
  }

  public void unsetChunkId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CHUNKID_ISSET_ID);
  }

  /** Returns true if field chunkId is set (has been assigned a value) and false otherwise */
  public boolean isSetChunkId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CHUNKID_ISSET_ID);
  }

  public void setChunkIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CHUNKID_ISSET_ID, value);
  }

  public int getVarEventMapSize() {
    return (this.varEventMap == null) ? 0 : this.varEventMap.size();
  }

  public void putToVarEventMap(java.lang.String key, java.nio.ByteBuffer val) {
    if (this.varEventMap == null) {
      this.varEventMap = new java.util.HashMap<java.lang.String,java.nio.ByteBuffer>();
    }
    this.varEventMap.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.nio.ByteBuffer> getVarEventMap() {
    return this.varEventMap;
  }

  public PushPullDataChunk setVarEventMap(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.nio.ByteBuffer> varEventMap) {
    this.varEventMap = varEventMap;
    return this;
  }

  public void unsetVarEventMap() {
    this.varEventMap = null;
  }

  /** Returns true if field varEventMap is set (has been assigned a value) and false otherwise */
  public boolean isSetVarEventMap() {
    return this.varEventMap != null;
  }

  public void setVarEventMapIsSet(boolean value) {
    if (!value) {
      this.varEventMap = null;
    }
  }

  public boolean isIsLastChunk() {
    return this.isLastChunk;
  }

  public PushPullDataChunk setIsLastChunk(boolean isLastChunk) {
    this.isLastChunk = isLastChunk;
    setIsLastChunkIsSet(true);
    return this;
  }

  public void unsetIsLastChunk() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISLASTCHUNK_ISSET_ID);
  }

  /** Returns true if field isLastChunk is set (has been assigned a value) and false otherwise */
  public boolean isSetIsLastChunk() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISLASTCHUNK_ISSET_ID);
  }

  public void setIsLastChunkIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISLASTCHUNK_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CHUNK_ID:
      if (value == null) {
        unsetChunkId();
      } else {
        setChunkId((java.lang.Integer)value);
      }
      break;

    case VAR_EVENT_MAP:
      if (value == null) {
        unsetVarEventMap();
      } else {
        setVarEventMap((java.util.Map<java.lang.String,java.nio.ByteBuffer>)value);
      }
      break;

    case IS_LAST_CHUNK:
      if (value == null) {
        unsetIsLastChunk();
      } else {
        setIsLastChunk((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CHUNK_ID:
      return getChunkId();

    case VAR_EVENT_MAP:
      return getVarEventMap();

    case IS_LAST_CHUNK:
      return isIsLastChunk();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CHUNK_ID:
      return isSetChunkId();
    case VAR_EVENT_MAP:
      return isSetVarEventMap();
    case IS_LAST_CHUNK:
      return isSetIsLastChunk();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PushPullDataChunk)
      return this.equals((PushPullDataChunk)that);
    return false;
  }

  public boolean equals(PushPullDataChunk that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_chunkId = true;
    boolean that_present_chunkId = true;
    if (this_present_chunkId || that_present_chunkId) {
      if (!(this_present_chunkId && that_present_chunkId))
        return false;
      if (this.chunkId != that.chunkId)
        return false;
    }

    boolean this_present_varEventMap = true && this.isSetVarEventMap();
    boolean that_present_varEventMap = true && that.isSetVarEventMap();
    if (this_present_varEventMap || that_present_varEventMap) {
      if (!(this_present_varEventMap && that_present_varEventMap))
        return false;
      if (!this.varEventMap.equals(that.varEventMap))
        return false;
    }

    boolean this_present_isLastChunk = true;
    boolean that_present_isLastChunk = true;
    if (this_present_isLastChunk || that_present_isLastChunk) {
      if (!(this_present_isLastChunk && that_present_isLastChunk))
        return false;
      if (this.isLastChunk != that.isLastChunk)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + chunkId;

    hashCode = hashCode * 8191 + ((isSetVarEventMap()) ? 131071 : 524287);
    if (isSetVarEventMap())
      hashCode = hashCode * 8191 + varEventMap.hashCode();

    hashCode = hashCode * 8191 + ((isLastChunk) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(PushPullDataChunk other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetChunkId(), other.isSetChunkId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChunkId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.chunkId, other.chunkId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVarEventMap(), other.isSetVarEventMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVarEventMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.varEventMap, other.varEventMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIsLastChunk(), other.isSetIsLastChunk());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsLastChunk()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isLastChunk, other.isLastChunk);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PushPullDataChunk(");
    boolean first = true;

    sb.append("chunkId:");
    sb.append(this.chunkId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("varEventMap:");
    if (this.varEventMap == null) {
      sb.append("null");
    } else {
      sb.append(this.varEventMap);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isLastChunk:");
    sb.append(this.isLastChunk);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PushPullDataChunkStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PushPullDataChunkStandardScheme getScheme() {
      return new PushPullDataChunkStandardScheme();
    }
  }

  private static class PushPullDataChunkStandardScheme extends org.apache.thrift.scheme.StandardScheme<PushPullDataChunk> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PushPullDataChunk struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CHUNK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.chunkId = iprot.readI32();
              struct.setChunkIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VAR_EVENT_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map28 = iprot.readMapBegin();
                struct.varEventMap = new java.util.HashMap<java.lang.String,java.nio.ByteBuffer>(2*_map28.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key29;
                @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer _val30;
                for (int _i31 = 0; _i31 < _map28.size; ++_i31)
                {
                  _key29 = iprot.readString();
                  _val30 = iprot.readBinary();
                  struct.varEventMap.put(_key29, _val30);
                }
                iprot.readMapEnd();
              }
              struct.setVarEventMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_LAST_CHUNK
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isLastChunk = iprot.readBool();
              struct.setIsLastChunkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PushPullDataChunk struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CHUNK_ID_FIELD_DESC);
      oprot.writeI32(struct.chunkId);
      oprot.writeFieldEnd();
      if (struct.varEventMap != null) {
        oprot.writeFieldBegin(VAR_EVENT_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.varEventMap.size()));
          for (java.util.Map.Entry<java.lang.String, java.nio.ByteBuffer> _iter32 : struct.varEventMap.entrySet())
          {
            oprot.writeString(_iter32.getKey());
            oprot.writeBinary(_iter32.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_LAST_CHUNK_FIELD_DESC);
      oprot.writeBool(struct.isLastChunk);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PushPullDataChunkTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PushPullDataChunkTupleScheme getScheme() {
      return new PushPullDataChunkTupleScheme();
    }
  }

  private static class PushPullDataChunkTupleScheme extends org.apache.thrift.scheme.TupleScheme<PushPullDataChunk> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PushPullDataChunk struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetChunkId()) {
        optionals.set(0);
      }
      if (struct.isSetVarEventMap()) {
        optionals.set(1);
      }
      if (struct.isSetIsLastChunk()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetChunkId()) {
        oprot.writeI32(struct.chunkId);
      }
      if (struct.isSetVarEventMap()) {
        {
          oprot.writeI32(struct.varEventMap.size());
          for (java.util.Map.Entry<java.lang.String, java.nio.ByteBuffer> _iter33 : struct.varEventMap.entrySet())
          {
            oprot.writeString(_iter33.getKey());
            oprot.writeBinary(_iter33.getValue());
          }
        }
      }
      if (struct.isSetIsLastChunk()) {
        oprot.writeBool(struct.isLastChunk);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PushPullDataChunk struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.chunkId = iprot.readI32();
        struct.setChunkIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map34 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING); 
          struct.varEventMap = new java.util.HashMap<java.lang.String,java.nio.ByteBuffer>(2*_map34.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key35;
          @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer _val36;
          for (int _i37 = 0; _i37 < _map34.size; ++_i37)
          {
            _key35 = iprot.readString();
            _val36 = iprot.readBinary();
            struct.varEventMap.put(_key35, _val36);
          }
        }
        struct.setVarEventMapIsSet(true);
      }
      if (incoming.get(2)) {
        struct.isLastChunk = iprot.readBool();
        struct.setIsLastChunkIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

